export const USER_ROOMS_REQUEST = "USER_ROOMS_REQUEST"
export const USER_ROOMS_SUCCESS = "USER_ROOMS_SUCCESS"
export const USER_ROOMS_FAIL = "USER_ROOMS_FAIL"

export const NEW_ROOM_REQUEST = "NEW_ROOM_REQUEST"
export const NEW_ROOM_SUCCESS = "NEW_ROOM_SUCCESS"
export const NEW_ROOM_FAIL = "NEW_ROOM_FAIL"

export const JOIN_ROOM_REQUEST = "JOIN_ROOM_REQUEST"
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS"
export const JOIN_ROOM_FAIL = "JOIN_ROOM_FAIL"

export const ROOM_DETAILS_REQUEST = "ROOM_DETAILS_REQUEST"
export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS"
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL"

export const EXIT_ROOM_REQUEST = "EXIT_ROOM_REQUEST"
export const EXIT_ROOM_SUCCESS = "EXIT_ROOM_SUCCESS"
export const EXIT_ROOM_FAIL = "EXIT_ROOM_FAIL"

export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST"
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS"
export const DELETE_ROOM_FAIL = "DELETE_ROOM_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";