export const ROOM_MESSAGES_REQUEST = "ROOM_MESSAGES_REQUEST"
export const ROOM_MESSAGES_SUCCESS = "ROOM_MESSAGES_SUCCESS"
export const UPDATE_ROOM_MESSAGES_SUCCESS = "UPDATE_ROOM_MESSAGES_SUCCESS"
export const ROOM_MESSAGES_FAIL = "ROOM_MESSAGES_FAIL"

export const NEW_MESSAGE_REQUEST = "NEW_MESSAGE_REQUEST";
export const NEW_MESSAGE_SUCCESS = "NEW_MESSAGE_SUCCESS";
export const NEW_MESSAGE_FAIL = "NEW_MESSAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";